- name: sample
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: print url
      vars:
        URL: tasks.google.com
      ansible.builtin.debug:
        msg: "{{ URL  }}"
  

- name: Task variables
  hosts: localhost
  connection: local
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: {{ URL }}
      vars:
        URL: task.level

- name: role variables
  hosts: localhost
  connection: local
  roles:
    - demo
